### ISSUE TITLE
Support numeric(..) and character(..)

### ISSUE THREAD

**Issue by horgh** [braintree/pg_column_byte_packer#2]
Hi! Awesome gem :-).

I was trying it out on one of my tables and I noticed it doesn't yet handle `numeric(20,3)` or `character(1)` columns:

```
pg_column_byte_packer.rb:115:in `ordering_key_for_column': Got sql_type: `numeric(20,3)` and type_schema: `pg_catalog` but was unable to find entry in pg_type. (ArgumentError)
```

I'm using a call to `PgColumnBytePacker::PgDump.sort_columns_for_definition_file` in my test.

**Comment by jcoleman** [comment]
Thanks for the feedback!

I'll try to take a look at this in a bit; most types we can handle automatically based on metadata from the PG catalog tables, but ones with `(...)` suffixes are special, so I think we just need to handle `numeric` and `character` specially.

**Comment by horgh** [comment]
Awesome, thank you!

**Comment by jcoleman** [comment]
@horgh I haven't yet released a new version because I'm hoping to look at one more thing before then, but if you need a release sooner rather than later, let us know.

**Comment by horgh** [comment]
That's okay! But thank you!

**Comment by jcoleman** [comment]
@horgh Sorry for the delay; I've pushed 1.1.0 which should include this fix.
